server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: 8080

spring:
  datasource:
    username: dusabe
    password: rdowssap
    url: jdbc:postgresql://localhost:7200/java
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  security:

    user:
      password: rdowssap
      name: dusabe
  mail:
    host: smtp.gmail.com
    port: 587
    username: elissafirstborn@gmail.com
    password: fyuf afwl ickn lgul
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:true
            required:true
        transport:
          protocol:smtp
  mvc:
    throw-exception-if-no-handler-found: true
jwt:
  secret:theemperor
  expiration:86400000

